// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sinesify;

#nullable disable

namespace Sinestify.Migrations
{
    [DbContext(typeof(ContextoSinestify))]
    [Migration("20260908013113_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Sinesify.Emocao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Sentimento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Emocoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Sentimento = "Alegria"
                        },
                        new
                        {
                            Id = 2,
                            Sentimento = "Tristeza"
                        },
                        new
                        {
                            Id = 3,
                            Sentimento = "Euforia"
                        },
                        new
                        {
                            Id = 4,
                            Sentimento = "Saudade"
                        },
                        new
                        {
                            Id = 5,
                            Sentimento = "Calma"
                        },
                        new
                        {
                            Id = 6,
                            Sentimento = "Nostalgia"
                        },
                        new
                        {
                            Id = 7,
                            Sentimento = "Esperança"
                        },
                        new
                        {
                            Id = 8,
                            Sentimento = "Melancolia"
                        },
                        new
                        {
                            Id = 9,
                            Sentimento = "Empolgação"
                        },
                        new
                        {
                            Id = 10,
                            Sentimento = "Romantismo"
                        });
                });

            modelBuilder.Entity("Sinesify.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Pop"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Rock"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Eletrônica"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "R&B"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Clássica"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Hip Hop"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Jazz"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Reggae"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Funk"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Country"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Indie"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Metal"
                        });
                });

            modelBuilder.Entity("Sinesify.Musica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cantor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EmocaoId")
                        .HasColumnType("int");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Velocidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmocaoId");

                    b.HasIndex("GeneroId");

                    b.ToTable("Musicas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantor = "Imagine Dragons",
                            EmocaoId = 3,
                            GeneroId = 2,
                            Nome = "Believer",
                            Velocidade = 120
                        },
                        new
                        {
                            Id = 2,
                            Cantor = "Imagine Dragons",
                            EmocaoId = 3,
                            GeneroId = 2,
                            Nome = "Thunder",
                            Velocidade = 118
                        },
                        new
                        {
                            Id = 3,
                            Cantor = "Ed Sheeran",
                            EmocaoId = 1,
                            GeneroId = 1,
                            Nome = "Shape Of You",
                            Velocidade = 76
                        },
                        new
                        {
                            Id = 4,
                            Cantor = "OneRepublic",
                            EmocaoId = 5,
                            GeneroId = 11,
                            Nome = "Counting Stars",
                            Velocidade = 94
                        },
                        new
                        {
                            Id = 5,
                            Cantor = "Ed Sheeran",
                            EmocaoId = 1,
                            GeneroId = 1,
                            Nome = "Perfect",
                            Velocidade = 48
                        },
                        new
                        {
                            Id = 6,
                            Cantor = "The Weeknd",
                            EmocaoId = 4,
                            GeneroId = 3,
                            Nome = "Blinding Lights",
                            Velocidade = 65
                        },
                        new
                        {
                            Id = 7,
                            Cantor = "Adele",
                            EmocaoId = 2,
                            GeneroId = 5,
                            Nome = "Someone Like You",
                            Velocidade = 40
                        },
                        new
                        {
                            Id = 8,
                            Cantor = "Linkin Park",
                            EmocaoId = 2,
                            GeneroId = 12,
                            Nome = "Numb",
                            Velocidade = 90
                        },
                        new
                        {
                            Id = 9,
                            Cantor = "Imagine Dragons",
                            EmocaoId = 4,
                            GeneroId = 2,
                            Nome = "Radioactive",
                            Velocidade = 100
                        },
                        new
                        {
                            Id = 10,
                            Cantor = "Coldplay",
                            EmocaoId = 1,
                            GeneroId = 11,
                            Nome = "Viva La Vida",
                            Velocidade = 110
                        },
                        new
                        {
                            Id = 11,
                            Cantor = "Bob Marley",
                            EmocaoId = 1,
                            GeneroId = 8,
                            Nome = "Three Little Birds",
                            Velocidade = 76
                        },
                        new
                        {
                            Id = 12,
                            Cantor = "Mark Ronson feat. Bruno Mars",
                            EmocaoId = 3,
                            GeneroId = 9,
                            Nome = "Uptown Funk",
                            Velocidade = 115
                        },
                        new
                        {
                            Id = 13,
                            Cantor = "John Denver",
                            EmocaoId = 1,
                            GeneroId = 10,
                            Nome = "Take Me Home, Country Roads",
                            Velocidade = 82
                        },
                        new
                        {
                            Id = 14,
                            Cantor = "Coldplay",
                            EmocaoId = 10,
                            GeneroId = 1,
                            Nome = "Yellow",
                            Velocidade = 87
                        },
                        new
                        {
                            Id = 15,
                            Cantor = "Coldplay",
                            EmocaoId = 8,
                            GeneroId = 11,
                            Nome = "The Scientist",
                            Velocidade = 73
                        },
                        new
                        {
                            Id = 16,
                            Cantor = "Journey",
                            EmocaoId = 7,
                            GeneroId = 4,
                            Nome = "Don't Stop Believin'",
                            Velocidade = 119
                        },
                        new
                        {
                            Id = 17,
                            Cantor = "Bryan Adams",
                            EmocaoId = 6,
                            GeneroId = 4,
                            Nome = "Summer Of '69",
                            Velocidade = 138
                        },
                        new
                        {
                            Id = 18,
                            Cantor = "Red Hot Chili Peppers",
                            EmocaoId = 9,
                            GeneroId = 12,
                            Nome = "Can't Stop",
                            Velocidade = 91
                        },
                        new
                        {
                            Id = 19,
                            Cantor = "Avicii",
                            EmocaoId = 7,
                            GeneroId = 7,
                            Nome = "Wake Me Up",
                            Velocidade = 124
                        },
                        new
                        {
                            Id = 20,
                            Cantor = "Guns N' Roses",
                            EmocaoId = 6,
                            GeneroId = 4,
                            Nome = "Sweet Child O' Mine",
                            Velocidade = 125
                        });
                });

            modelBuilder.Entity("Sinesify.Musica", b =>
                {
                    b.HasOne("Sinesify.Emocao", "Emocao")
                        .WithMany("Musicas")
                        .HasForeignKey("EmocaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sinesify.Genero", "Genero")
                        .WithMany("Musicas")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emocao");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("Sinesify.Emocao", b =>
                {
                    b.Navigation("Musicas");
                });

            modelBuilder.Entity("Sinesify.Genero", b =>
                {
                    b.Navigation("Musicas");
                });
#pragma warning restore 612, 618
        }
    }
}
